<a href="https://colab.research.google.com/github/annuss5/Colab-Works/blob/main/Numpytutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**E.Annapoorna**


**Tag-N**

In [1]:
import numpy as np

In [2]:
myPythonlist=[1,7,8,6]
print(myPythonlist)

[1, 7, 8, 6]


In [3]:
array_from_list=np.array(myPythonlist)
array_from_list

array([1, 7, 8, 6])

In [4]:
a=np.array([1,7,8,6])
print(a)

[1 7 8 6]


In [5]:
x=array_from_list + 10
print(x)

[11 17 18 16]


In [6]:
a=np.array([1,4,5])
print(a.shape)
print(a.dtype)

(3,)
int64


In [7]:
b=np.array([1,4.4,5])
print(b.dtype)

float64


In [9]:
c=np.array([(1,2,3),(4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [10]:
d=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(d.shape)

(1, 4, 3)


In [13]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)


[[0 0]
 [0 0]]


In [17]:
import numpy as np
e=np.array([(1,2,3),(4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

In [19]:
import numpy as np
f=np.array([1,2,3])
g=np.array([4,5,6])
print('Hor.append : ' , np.hstack((f,g)))

Hor.append :  [1 2 3 4 5 6]


In [20]:
import numpy as np
f=np.array([1,2,3])
g=np.array([4,5,6])
print('Ver.append : ' , np.vstack((f,g)))

Ver.append :  [[1 2 3]
 [4 5 6]]


In [21]:
normal_array=np.random.normal(2,0.2,4)
print(normal_array)

[2.21380681 1.98233556 1.88712885 1.76969229]


In [24]:
A=np.matrix(np.ones((4,4)))
np.array(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
np.asarray(A)[2]=2
print(A)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [27]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(0,16,5)

array([ 0,  5, 10, 15])

In [29]:
import numpy as np
np.linspace(1.0,10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [30]:
np.logspace(3.0,4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [31]:
x=np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

In [2]:
import numpy as np
e=np.array([(1,2,3),(4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [6]:
print('first row : ', e[0] )
print('second row : ',e[1])

first row :  [1 2 3]
second row :  [4 5 6]


In [7]:
print('2nd column : ' ,e[:,1])

2nd column :  [2 5]


In [8]:
print(e[1,:2])

[4 5]


In [9]:
import numpy as np
normal_array=np.random.normal(5,0.5,10)
print(normal_array)

[4.33611828 4.45854663 6.30667803 4.75817793 5.14553253 5.09263007
 4.59025034 5.19877433 4.8157767  5.16551305]


In [10]:
print(np.min(normal_array))
print(np.max(normal_array))
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

4.3361182817566055
6.306678025074024
4.986799786303932
4.954203381568055
0.5288244010155227


In [12]:
import numpy as np
f=np.array([1,2])
g=np.array([4,5])
np.dot(f,g)

14

In [15]:
import numpy as np
h=[[1,2],[3,4]]
i=[[5,6],[7,8]]
np.matmul(h,i)

array([[19, 22],
       [43, 50]])

In [16]:
A=np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [17]:
n_array=np.array([[50,29],[30,44]])
det=np.linalg.det(n_array)
print("\nDeterminant is: ")
print(int(det))


Determinant is: 
1330


In [18]:
mx=np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("\nRank is : ")
np.linalg.matrix_rank(mx)


Rank is : 


3

In [24]:
A=np.matrix('[6,2 ; 3, 4]')
diag=A.diagonal()
print(diag)

[[6 4]]


In [25]:
A=np.matrix([[6,1,1],[4,-2,5],[2,8,7]])
A.transpose()

matrix([[ 6,  4,  2],
        [ 1, -2,  8],
        [ 1,  5,  7]])

In [27]:
A=np.matrix([[6,1,1],[4,-2,5],[2,8,7]])

np.linalg.eig(A)

(array([11.24862343,  5.09285054, -5.34147398]),
 matrix([[ 0.24511338,  0.75669314,  0.02645665],
         [ 0.40622202, -0.03352363, -0.84078293],
         [ 0.88028581, -0.65291014,  0.54072554]]))

In [29]:
gfg=np.matrix('[4,1 ; 6, 5]')
gfg.trace()

matrix([[9]])